name: TRLC Extension Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:

  package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fetch CVC5 (OSX)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-macOS"
          out-file-path: "bin"
      - name: Fetch CVC5 (Windows)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-Win64.exe"
          out-file-path: "bin"
      - name: Fetch CVC5 (Linux)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "cvc5/cvc5"
          tag: "cvc5-1.0.8"
          fileName: "cvc5-Linux"
          out-file-path: "bin"
      - name: Set permissions
        run: |
          chmod +x bin/*
      - name: "Build package"
        run: |
          python3 -m pip install --upgrade pip
          make install-python-deps
          npm install @vscode/vsce
          npx vsce package
      - name: "Archive package"
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: "*.vsix"
